### ISSUE TITLE
Warning Message: Creating default object from empty value

### ISSUE THREAD

**Issue by ruddj** [marxjohnson/moodle-block_metalink#4]
The block is generating the warning:
Warning: Creating default object from empty value in /moodle/blocks/metalink/block_metalink.php on line 66

This can be easily fixed by inserting the following at line 66

```
        $this->content = new stdClass();
```

**Comment by drjosephbaxter** [comment]
Is there an ETA on this fix. 

Here at the University of Nottingham we are looking into the compatibility with moodle 2.6 so we could contribute the fix to community plugin if it is still active?

**Comment by drjosephbaxter** [comment]
Should be resolved in Build: 2014060911

**Comment by ruddj** [comment]
Line that has been added should fix the issue. Thanks for the update to the project.
